/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.ClienteDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
import util.ConnectionFactory;

/**
 *
 * @author Dayana
 */
public class ConsultaCliente extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaCliente
     */
    public ConsultaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Sexo", "Estado  Civil", "Endereço", "Complemento", "Bairro", "CEP", "Cidade", "Estado", "Número", "CPF", "RG", "Telefone", "Celular", "E-mail", "Data de nascimento", "Data de Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);
        if (tabelaCliente.getColumnModel().getColumnCount() > 0) {
            tabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaCliente.getColumnModel().getColumn(1).setPreferredWidth(250);
            tabelaCliente.getColumnModel().getColumn(2).setPreferredWidth(65);
            tabelaCliente.getColumnModel().getColumn(3).setPreferredWidth(90);
            tabelaCliente.getColumnModel().getColumn(4).setPreferredWidth(250);
            tabelaCliente.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabelaCliente.getColumnModel().getColumn(6).setPreferredWidth(150);
            tabelaCliente.getColumnModel().getColumn(7).setPreferredWidth(80);
            tabelaCliente.getColumnModel().getColumn(8).setPreferredWidth(150);
            tabelaCliente.getColumnModel().getColumn(9).setPreferredWidth(150);
            tabelaCliente.getColumnModel().getColumn(10).setPreferredWidth(50);
            tabelaCliente.getColumnModel().getColumn(11).setPreferredWidth(100);
            tabelaCliente.getColumnModel().getColumn(12).setPreferredWidth(60);
            tabelaCliente.getColumnModel().getColumn(13).setPreferredWidth(90);
            tabelaCliente.getColumnModel().getColumn(14).setPreferredWidth(90);
            tabelaCliente.getColumnModel().getColumn(15).setPreferredWidth(180);
            tabelaCliente.getColumnModel().getColumn(16).setPreferredWidth(120);
            tabelaCliente.getColumnModel().getColumn(17).setPreferredWidth(120);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        try {

            String nome = txtNome.getText();//capturando o que se escreve na tela

            Connection bd = ConnectionFactory.getConection();

            ClienteDAO clienteDao = new ClienteDAO(bd);
            List<Cliente> lista = clienteDao.consultarClientes(nome);
            popularTabela(lista);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtNomeKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            if(tabelaCliente.getSelectedRow()== 1){//selecione uma linha - selected row retorna a quantidade de linhas selecionado
                Connection bd = ConnectionFactory.getConection();
                ClienteDAO clienteDao = new ClienteDAO(bd);
                Long codigo = Long.parseLong(tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0) + "");
                clienteDao.excluir(codigo);

                ((DefaultTableModel) tabelaCliente.getModel()).removeRow(tabelaCliente.getSelectedRow());
                tabelaCliente.repaint();// recarrega tabela
                tabelaCliente.revalidate();
            }else{
                JOptionPane.showMessageDialog(null, "Selecione ao menos um registro para excluir!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new CadastroCliente().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //alterar
        if(tabelaCliente.getSelectedRowCount()== 1){
            try {
                Cliente cliente = new Cliente();
                cliente.setCodigo(Integer.parseInt((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 0)));
                cliente.setNome((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 1));
                cliente.setSexo((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 2));
                cliente.setEstadoCivil((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 3));
                cliente.setEndereco((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 4));
                cliente.setComplemento((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 5));
                cliente.setBairro((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 6));
                cliente.setCep((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 7));
                cliente.setCidade((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 8));
                cliente.setEstado((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 9));
                cliente.setNumero((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 10));
                cliente.setCpf((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 11));
                cliente.setRg((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 12));
                cliente.setTelefone((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 13));
                cliente.setCelular((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 14));
                cliente.setEmail((String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 15));
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String dtNascimento = (String)tabelaCliente.getValueAt(tabelaCliente.getSelectedRow(), 16);
                System.out.println(dtNascimento);
                cliente.setDataNascimento(sdf.parse(dtNascimento));
                new CadastroCliente(cliente).setVisible(true);
                dispose();
                
                
            } catch (ParseException ex) {
                Logger.getLogger(ConsultaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um único registro para alterar.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void popularTabela(List<Cliente> lista) {
        tabelaCliente.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);//padrão
        DefaultTableModel modelo = (DefaultTableModel) tabelaCliente.getModel();
        modelo.setNumRows(0);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        lista.stream().forEach((Cliente c) -> {
            modelo.addRow(new String[]{c.getCodigo() + "", c.getNome(), c.getSexo().equals("M") ? "Masculino" : "Feminino", c.getEstadoCivil(), c.getEndereco(), 
                c.getComplemento(), c.getBairro(), c.getCep(), c.getCidade(), c.getEstado(), c.getNumero(),  c.getCpf(), c.getRg(),c.getTelefone(), c.getCelular(), c.getEmail(), 
                sdf.format(c.getDataNascimento()), sdf.format(c.getDataCadastro())});
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
